### ISSUE TITLE
new feature: team page

### ISSUE THREAD

**Issue by robert-weissgraeber** [aexeagmbh/docker-wagtail-www#1]
Ziel: eine Liste von Team-Mitgliedern auf der Seite, mit Photo, Name, Titel/Funktion

Ideen:
- zB so: http://zurb.com/patterntap/pattern/team-page-bkwld
- http://zurb.com/patterntap/pattern/team-page-life-thyme

Funktion:
- pflegen mit Mitarbeitern als Datensätze in Wagtail
- Anzeige auf einer Seite oder als Teil einer Seite?

**Comment by maddesigns** [comment]
brauchst du da noch andere Icons oder reichen die, die wir schon haben?

**Comment by maddesigns** [comment]
wie könnte die Smartphone-Ansicht aussehen? Alles untereinander? Finde ich immer ein wenig langweilig. Ich könnte mir vorstellen, dass man 2 Spalten, aber die Bilder hochkannt beschneidet. Muss man mal probieren, was da gut aussieht…

**Comment by robert-weissgraeber** [comment]
icons: linkedin/Xing kommt wahrscheinlich irgendwann, aber gerade Prio 2.

smartphone: bilder deutlich kleiner, und evtl. hin zu einer Bild-Text liste.

**Comment by robert-weissgraeber** [comment]
done. badly, but done.
