### ISSUE TITLE
add new page template with "streamfield" feature

### ISSUE THREAD

**Issue by robert-weissgraeber** [aexeagmbh/docker-wagtail-www#11]
allow the following block types:

## prio "next"
- [x] header (title/green bar, background image)
- [x] teaser area (grey background)
- [x] 1-column text 
- [x] 2-column text 50-50
- [x] call-to-action bar (title, button+link, dark background

## prio "thereafter"
- [x] 2-column text 66-33
- [x] 3-column text 33-33-33
- [x] HTML Fields

## prio "later"
- [x] quote feature (like https://www.ax-semantics.com/products/e-commerce-content/)
- [ ] team-members

## maybe?
- [ ] form wizard (?)

**Comment by asmaps** [comment]
"next", "thereafter" and quotation from "later" are on production now
