### ISSUE TITLE
spacing in multi column layout

### ISSUE THREAD

**Issue by robert-weissgraeber** [aexeagmbh/docker-wagtail-www#23]
- [x] add space around images
- [x] add top/bottom space

![image](https://cloud.githubusercontent.com/assets/6907834/10539707/e284a4d8-7401-11e5-9a8b-5490ef7c29d2.png)

**Comment by asmaps** [comment]
fixed in dc99c16cac072b39d4cd0e9380883038b5982353 and f3d20e57ce69d4da2c7e59000e6559816aae9b0e
