### ISSUE TITLE
make background for content elements a real white - easier use of logos

### ISSUE THREAD

**Issue by robert-weissgraeber** [aexeagmbh/docker-wagtail-www#25]
because of the mininmal grey tint, logos are hard to use if they have white background.

change backgrund in content areas to white:

![image](https://cloud.githubusercontent.com/assets/6907834/10540081/e269bc74-7404-11e5-8514-b407a8f37a60.png)

**Comment by asmaps** [comment]
fixed by f41d73901b07f7f90f0545a5de622deccf4fbad9
