### ISSUE TITLE
Uneven spacing on duplicate-button

### ISSUE THREAD

**Issue by robert-weissgraeber** [aexeagmbh/docker-wagtail-www#27]
- vertical spacing should be the same
- increate horizontal space between buttons

![image](https://cloud.githubusercontent.com/assets/6907834/10540520/0659f5fa-7409-11e5-8921-4f4ad4d1a4a0.png)

**Comment by asmaps** [comment]
fixed in fd1b8bb0fc3e7961840cdd1f7ded00daf807c29d
