### ISSUE TITLE
makes it look broken

### ISSUE THREAD

**Issue by b-times-b** [aexeagmbh/docker-wagtail-www#32]
- sprachwechsler ueberlagert logo in tablett / mobil ansicht
- team page kontakt slider bei mitarbeitern sieht in unterschiedlichen aufloesungen kaputt aus
- team page js broken in ff: ReferenceError: event is not defined ...var animateElements=function(that){event.preventDefault();var icon1=that.fin...

**Comment by robert-weissgraeber** [comment]
egal for now
