### ISSUE TITLE
Does it make sense to make API docs more prominent in MyAX?

### ISSUE THREAD

**Issue by frank-feulner** [aexeagmbh/docker-wagtail-www#36]
*Current*
API Documentation is available via apidocs.ax-semantics.com
Path to link is Click top right - Click account name - click link to apidocs.

*Desirable*
API Documentation is available in one click. E.g. in the footer area with the example calls.

**Comment by robert-weissgraeber** [comment]
wrong repo, this is the website ;) - should be in morgana, but github does not allow issue move.

maybe add a link to the api-footer on morgana?

**Comment by robert-weissgraeber** [comment]
fixed by: https://github.com/aexeagmbh/morgana/commit/928976874e24b76665362be09552499e51c4f32e
