### ISSUE TITLE
AX-Blog auf Website unterbringen

### ISSUE THREAD

**Issue by ASaexea** [aexeagmbh/docker-wagtail-www#6]
Das AX-Blog sollte auch direkt über die Website erreichbar sein. Als Menüpunkt unterbringen, wäre cool. Danke + liebe Grüße
Adela

**Comment by robert-weissgraeber** [comment]
Ist aktuell schon drin, ganz unten auf jeder Seite, im Footer.

was wir noch machen ist den feed anzuzeigen auf macnhen seiten,  das hat aber aktuell keine hohe  Prio.

**Comment by ASaexea** [comment]
Wäre schön, wenn er einfach oben im Menü zu finden ist (auf vielen Websites als Unterpunkt von about). Wir haben gerade mit deinem Hinweis zu dritt minutenlang gesucht...
Aber auch aus SEO-Gründen wäre es gut, wenn es gut eingebunden wäre (dann kann man z.B. flexibel auf Suchanfragen/Keywords reagieren)...

**Comment by asmaps** [comment]
Es gibt kein about :-)
